const express = require('express');
const exphbs = require('express-handlebars');
const sequelize = require('./config/bd');
const Produto = require('./models/produto.model');
const Categoria = require('./models/categoria.model');
const Tamanho = require('./models/tamanho.model');
const methodOverride = require('method-override');
require('./models/relacionamentosModels');

const app = express();

app.use(methodOverride('_method'));

// Middleware para formulário
app.use(express.urlencoded({ extended: true }));
app.use(express.json());

// Configurando Handlebars
app.engine('handlebars', exphbs.engine({
  defaultLayout: false,
  helpers: {
    eq: (v1, v2) => v1 == v2
  }
}));

app.set('view engine', 'handlebars');

// Página inicial
app.get('/', (req, res) => res.render('home', { titulo: 'Página Inicial' }));

// ---------- Produtos ----------
app.get('/produtos', async (req, res) => {
  const produtos = await Produto.findAll({ raw: true });
  res.render('produtos', { produtos });
});

app.get('/produtos/cadastrar', async (req, res) => {
  const categorias = await Categoria.findAll({ raw: true });
  const tamanhos = await Tamanho.findAll({ raw: true });
  res.render('cadastrarprodutos', { categorias, tamanhos });
});

app.post('/produtos', async (req, res) => {
  const { nome, ano, categoriaId, tamanhos } = req.body;
  const produto = await Produto.create({ nome, ano, categoriaId });
  if (tamanhos && tamanhos.length > 0) {
    // setTamanhos generated by Sequelize from alias 'tamanhos'
    await produto.setTamanhos(Array.isArray(tamanhos) ? tamanhos : [tamanhos]);
  }
  res.redirect('/produtos');
});

app.get('/produtos/:id', async (req, res) => {
  const id = req.params.id;
  const produto = await Produto.findByPk(id, { include: [{ model: Categoria, as: 'categoria' }, { model: Tamanho, as: 'tamanhos' }] });
  res.render('detalharprodutos', { produtos: produto ? produto.toJSON() : null });
});

app.get('/produtos/:id/editar', async (req, res) => {
  const id = req.params.id;
  const produto = await Produto.findByPk(id, { raw: true });
  const categorias = await Categoria.findAll({ raw: true });
  const tamanhos = await Tamanho.findAll({ raw: true });
  res.render('editarprodutos', { produtos: produto, categorias, tamanhos });
});

app.put('/produtos/:id', async (req, res) => {
  const id = req.params.id;
  const { nome, ano, categoriaId, tamanhos } = req.body;
  const produto = await Produto.findByPk(id);
  if (produto) {
    produto.nome = nome;
    produto.ano = ano;
    produto.categoriaId = categoriaId;
    await produto.save();
    if (tamanhos && tamanhos.length > 0) {
      await produto.setTamanhos(Array.isArray(tamanhos) ? tamanhos : [tamanhos]);
    }
  }
  res.redirect('/produtos');
});

app.delete('/produtos/:id', async (req, res) => {
  const id = req.params.id;
  const produto = await Produto.findByPk(id);
  if (produto) await produto.destroy();
  res.redirect('/produtos');
});

// ---------- Categorias ----------
app.get('/categorias', async (req, res) => {
  const categorias = await Categoria.findAll({ raw: true });
  res.render('categorias', { categorias });
});

app.get('/categorias/cadastrar', (req, res) => res.render('cadastrarcategoria'));

app.post('/categorias', async (req, res) => {
  const { nome, anoNascimento, nacionalidade } = req.body;
  await Categoria.create({ nome, anoNascimento, nacionalidade });
  res.redirect('/categorias');
});

app.get('/categorias/:id', async (req, res) => {
  const id = req.params.id;
  const categoria = await Categoria.findByPk(id, { include: [{ model: Produto, as: 'produtos' }] });
  res.render('detalharcategoria', { categoria: categoria ? categoria.toJSON() : null });
});

app.get('/categorias/:id/editar', async (req, res) => {
  const id = req.params.id;
  const categoria = await Categoria.findByPk(id, { raw: true });
  res.render('editarcategoria', { categoria });
});

app.put('/categorias/:id', async (req, res) => {
  const id = req.params.id;
  const { nome, anoNascimento, nacionalidade } = req.body;
  const categoria = await Categoria.findByPk(id);
  if (categoria) {
    categoria.nome = nome;
    categoria.anoNascimento = anoNascimento;
    categoria.nacionalidade = nacionalidade;
    await categoria.save();
  }
  res.redirect('/categorias');
});

app.delete('/categorias/:id', async (req, res) => {
  const id = req.params.id;
  const categoria = await Categoria.findByPk(id);
  if (categoria) await categoria.destroy();
  res.redirect('/categorias');
});

// ---------- Tamanho ----------
app.get('/tamanho', async (req, res) => {
  const tamanhos = await Tamanho.findAll({ raw: true });
  res.render('tamanho', { tamanho: tamanhos });
});

app.get('/tamanho/cadastrar', async (req, res) => {
  const produtos = await Produto.findAll({ raw: true });
  res.render('cadastrartamanho', { produtos });
});

app.post('/tamanho', async (req, res) => {
  const { nome } = req.body;
  await Tamanho.create({ nome });
  res.redirect('/tamanho');
});

app.get('/tamanho/:id', async (req, res) => {
  const id = req.params.id;
  const tamanho = await Tamanho.findByPk(id, { include: [{ model: Produto, as: 'produtos' }] });
  res.render('detalharArtista', { artista: tamanho ? tamanho.toJSON() : null });
});

app.get('/tamanho/:id/editar', async (req, res) => {
  const id = req.params.id;
  const tamanho = await Tamanho.findByPk(id, { raw: true });
  const produtos = await Produto.findAll({ raw: true });
  res.render('editarArtista', { artista: tamanho, produtos });
});

app.put('/tamanho/:id', async (req, res) => {
  const id = req.params.id;
  const { nome } = req.body;
  const tamanho = await Tamanho.findByPk(id);
  if (tamanho) {
    tamanho.nome = nome;
    await tamanho.save();
  }
  res.redirect('/tamanho');
});

app.delete('/tamanho/:id', async (req, res) => {
  const id = req.params.id;
  const tamanho = await Tamanho.findByPk(id);
  if (tamanho) await tamanho.destroy();
  res.redirect('/tamanho');
});

// Conectar ao BD
async function conectarBD() {
  try {
    await sequelize.sync();
    console.log('Conexão com o banco de dados estabelecida com sucesso!');
  } catch (erro) {
    console.error('Erro ao conectar:', erro);
  }
}
conectarBD();

// Inicializando servidor
app.listen(3000, () => {
  console.log('Servidor executando em http://localhost:3000');
});
